#!/usr/bin/env python3
"""Independent hand-specified sensor-23 fixtures; no Android/protobuf required."""
import importlib.util
import json
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest

ROOT = Path(__file__).resolve().parents[4]
TOOL = ROOT / "tools/ev_vem_contract.py"

# External vehicle info: 50,000 Wh +/-10; 80,000 Wh +/-20; 25 C;
# deliberately unequal peak motor=300 W and max charging=150 W (synthetic).
# Road load: (100 +/-1), (2 +/-0.25), (0.5 +/-0.125). Units unresolved.
# Heat-pump capability is UNKNOWN: field 1.11 deliberately absent.
# These literal tags/lengths/values are not generated by any OAL encoder.
GOLDEN = bytes.fromhex(
    "0a21"
    "1a0908d086031500002041"
    "22090880f104150000a041"
    "450000c841"
    "48ac02"
    "509601"
    "1224"
    "0a0a0d0000c842150000803f"
    "120a0d00000040150000803e"
    "1a0a0d0000003f150000003e"
)


def load_tool():
    spec = importlib.util.spec_from_file_location("ev_vem_contract", TOOL)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class ExternalContractTest(unittest.TestCase):
    def test_independent_external_golden(self):
        self.assertTrue(TOOL.is_file(), "missing external wire inspector")
        report = load_tool().inspect_vem(GOLDEN)
        fields = {item["path"]: item for item in report["fields"]}
        expected = {
            "1.3.1": 50000, "1.3.2": 10.0,
            "1.4.1": 80000, "1.4.2": 20.0,
            "1.8": 25.0, "1.9": 300, "1.10": 150,
            "2.1.1": 100.0, "2.1.2": 1.0,
            "2.2.1": 2.0, "2.2.2": 0.25,
            "2.3.1": 0.5, "2.3.2": 0.125,
        }
        for path, value in expected.items():
            with self.subTest(path=path):
                self.assertEqual(fields[path]["value"], value)
                self.assertEqual(fields[path]["status"], "compatible")
        self.assertEqual(fields["1.9"]["name"], "peak_motor_power_w")
        self.assertEqual(fields["1.10"]["name"], "max_charging_rate_w")
        self.assertIn("1.11", report["absent"])
        self.assertNotIn("1.11", fields)  # absence is not false or true
        self.assertNotIn("1.1", fields)
        self.assertNotIn("12", fields)
        self.assertTrue(all(f["status"] == "compatible" for f in report["fields"]))

    def test_legacy_is_not_relabelled_as_a_valid_external_model(self):
        # config=1; reserve=1000 nested at 8; powers=300/150; regen=true;
        # top-level preferences mode=1. Literal legacy wire shapes.
        legacy = bytes.fromhex("0a0f0801420308e80748ac02509601580162021801")
        report = load_tool().inspect_vem(legacy)
        fields = {f["path"]: f for f in report["fields"]}
        self.assertEqual(fields["1.1"]["status"], "unknown")
        self.assertIn("absent", fields["1.1"]["note"])
        self.assertEqual(fields["1.8"]["status"], "wrong-wire")
        self.assertEqual(fields["1.8"]["expected_wire"], 5)
        self.assertEqual(fields["1.8"]["raw_hex"], "420308e807")
        self.assertNotIn("1.8.1", fields)  # never interpret reserve as temperature
        self.assertEqual(fields["12"]["status"], "unknown")
        self.assertEqual(fields["1.9"]["value"], 300)
        self.assertEqual(fields["1.10"]["value"], 150)
        self.assertEqual(fields["1.11"]["name"], "heat_pump_equipped")
        self.assertTrue(fields["1.11"]["value"])  # not a regen assertion
        # Unknown fields are retained, including opaque bytes that are not a message.
        opaque = bytes.fromhex("980607a1060001020304050607aa0602ff00b5060000803f")
        unknown = load_tool().inspect_vem(opaque)["fields"]
        self.assertEqual([f["path"] for f in unknown], ["99", "100", "101", "102"])
        self.assertTrue(all(f["status"] == "unknown" for f in unknown))
        self.assertEqual("".join(f["raw_hex"] for f in unknown), opaque.hex())
        # Absence is distinct from explicit known-false; duplicates stay observable.
        explicit = load_tool().inspect_vem(bytes.fromhex("0a0458005801"))
        self.assertEqual([f["value"] for f in explicit["fields"] if f["path"] == "1.11"],
                         [False, True])
        self.assertNotIn("1.11", explicit["absent"])

    def test_malformed_input_and_resource_limits_are_bounded(self):
        tool = load_tool()
        self.assertTrue(hasattr(tool, "WireError"), "missing bounded parse errors")
        malformed = {
            "zero field": "00", "zero field fixed32": "0500000000",
            "field number overflow": "808080801001",
            "truncated tag": "80", "truncated varint": "980680",
            "uint64 overflow": "9806ffffffffffffffffff02",
            "unterminated varint": "98068080808080808080808080",
            "truncated length": "0a80", "length past end": "0a02ff",
            "huge length": "0affffffffffffffffff01",
            "truncated fixed32": "b506000000", "truncated fixed64": "a106000000",
            "nested truncated value": "0a0118",
            "invalid wire 6": "0e", "invalid wire 7": "0f",
            "unsupported group": "0b0c", "unexpected end group": "0c",
        }
        for label, hex_data in malformed.items():
            with self.subTest(label=label):
                with self.assertRaises(tool.WireError):
                    tool.inspect_vem(bytes.fromhex(hex_data))
        self.assertEqual(tool.inspect_vem(b"")["fields"], [])
        for limits in ({"max_bytes": len(GOLDEN) - 1}, {"max_fields": 2},
                       {"max_depth": 1}):
            with self.subTest(limits=limits):
                with self.assertRaises(tool.WireError):
                    tool.inspect_vem(GOLDEN, **limits)
        self.assertTrue(tool.inspect_vem(GOLDEN, max_bytes=len(GOLDEN))["fields"])

    def test_scalar_domains_do_not_silently_truncate_power(self):
        tool = load_tool()
        # uint32 max, then 2**32 (valid uint64 wire but not uint32 contract).
        valid = tool.inspect_vem(bytes.fromhex("0a0648ffffffff0f"))["fields"][-1]
        self.assertEqual(valid["value"], 4294967295)
        invalid = tool.inspect_vem(bytes.fromhex("0a06508080808010"))["fields"][-1]
        self.assertEqual(invalid["status"], "invalid-value")
        self.assertEqual(invalid["value"], 4294967296)
        # Canonical protobuf int32 -1 is sign-extended to ten varint bytes.
        negative = tool.inspect_vem(bytes.fromhex("0a0d1a0b08ffffffffffffffffff01"))
        self.assertEqual(negative["fields"][-1]["value"], -1)
        # Zero energy is a representable value, not an omitted update.
        zero = tool.inspect_vem(bytes.fromhex("0a041a020800"))
        self.assertEqual(zero["fields"][-1]["value"], 0)
        # Finite wire floats are not a physical validation; nonfinite is flagged.
        nan = tool.inspect_vem(bytes.fromhex("0a05450000c07f"))["fields"][-1]
        self.assertEqual(nan["status"], "invalid-value")
        self.assertEqual(nan["value"], "nan")

    def test_cli_inspects_hex_and_bounded_binary_files_without_android(self):
        def run(*args):
            return subprocess.run([sys.executable, str(TOOL), *args],
                                  capture_output=True, text=True, timeout=5)

        result = run("--hex", GOLDEN.hex())
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertTrue(result.stdout.strip(), "missing JSON CLI")
        self.assertEqual(json.loads(result.stdout), load_tool().inspect_vem(GOLDEN))
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "synthetic-vem.bin"
            path.write_bytes(GOLDEN)
            self.assertEqual(json.loads(run("--file", str(path)).stdout),
                             json.loads(result.stdout))
            path.write_bytes(b"\x00" * 65537)
            self.assertEqual(run("--file", str(path)).returncode, 2)
        self.assertEqual(run("--hex", "0a05420308e807").returncode, 1)
        self.assertEqual(run("--hex", "0a06508080808010").returncode, 1)
        self.assertEqual(run("--hex", "980607").returncode, 0)  # unknown != incompatible
        for args in (("--hex", "zz"), ("--hex", "80"),
                     ("--file", str(path))):
            with self.subTest(args=args[:1]):
                failed = run(*args)
                self.assertEqual(failed.returncode, 2)
                self.assertIn("error", failed.stderr)
                self.assertNotIn("Traceback", failed.stderr)


if __name__ == "__main__":
    unittest.main()
